version: '3.8'

services:
  legal_discovery:
    build:
      context: .
      dockerfile: apps/legal_discovery/Dockerfile
    ports:
      - "8080:5001"
    volumes:
      - /mnt/e/docker_volumes/legal_discovery/uploads:/usr/src/app/uploads

  neo4j:
    image: neo4j:4.4
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/dAUypMUkdIYM8ikq72iHqXqCgvb7WojrLtszvDQa4Uo
    volumes:
      - /mnt/e/docker_volumes/neo4j/data:/data

  chromadb:
    image: chromadb/chroma
    ports:
      - "8000:8000"
    volumes:
      - /mnt/e/docker_volumes/chroma:/chroma_data

  tesseract:
    image: tesseractshadow/tesseract4re
    ports:
      - "5000:5000"

volumes:
  neo4j_data: - /mnt/e/docker_volumes/neo4j/data:/data
  uploads_data: - /mnt/e/docker_volumes/chroma:/chroma_data
